### PR TITLE
More consistency and automatic versioning

### PR DESCRIPTION
**Pull request by Willsr71**
Also badges.

### CODE REVIEW

**Comment by Willsr71** [comment]
Can one of the admins verify this patch?

**Comment by Vastrix** [comment]
@Willsr71 You're a "Collaborator" shouldn't you be able to directly push this? :o

**Comment by Willsr71** [comment]
Yes, but some changes im just putting in pull requests if they change a good deal of things. And
 apparently my Jenkins commented for me with the "Can one of the admins verify this patch" That will have to be dealt with.

**Comment by Vastrix** [comment]
:D

**Pull request merged**
